/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_kryo_free: (a: number, b: number) => void;
export const kryo_acknowledgeChange: (a: number, b: number, c: number) => [number, number];
export const kryo_addClaims: (a: number, b: number, c: number) => [number, number];
export const kryo_backupCreate: (a: number) => [number, number, number, number];
export const kryo_backupReseal: (a: number, b: number, c: number) => [number, number, number, number];
export const kryo_checkDevices: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const kryo_create: (a: number, b: number) => [number, number, number];
export const kryo_decode: (a: number, b: number) => [number, number, number, number];
export const kryo_decrypt: (a: number, b: number, c: number) => [number, number];
export const kryo_deviceId: (a: number) => [number, number];
export const kryo_forgetDevices: (a: number, b: number, c: number) => void;
export const kryo_hello: (a: number, b: number, c: number) => [number, number];
export const kryo_knownDevices: (a: number, b: number, c: number) => number;
export const kryo_markVerified: (a: number, b: number, c: number, d: number) => [number, number];
export const kryo_masterPublic: (a: number) => [number, number];
export const kryo_needsClaim: (a: number, b: number, c: number) => number;
export const kryo_newMessageId: () => [number, number];
export const kryo_openFile: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const kryo_proof: (a: number, b: number, c: number) => [number, number, number, number];
export const kryo_receiveRules: (a: number, b: number, c: number) => [number, number, number, number];
export const kryo_register: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const kryo_request: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const kryo_resetIdentity: (a: number) => void;
export const kryo_restore: (a: number, b: number) => [number, number, number];
export const kryo_restoreBackup: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const kryo_sealFile: (a: number, b: number) => [number, number, number, number];
export const kryo_sendFrame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const kryo_setDeviceId: (a: number, b: number, c: number) => [number, number];
export const kryo_state: (a: number) => [number, number, number, number];
export const kryo_userId: (a: number) => [number, number];
export const kryo_validate: (a: number, b: number, c: number) => [number, number];
export const kryo_verifyInfo: (a: number, b: number, c: number) => [number, number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
