// Trace kryo.to's K// mark into vector rectangles, so the client draws the
// site's real mark - not a lookalike - crisp at any size.
//
//   node scripts/trace-mark.mjs [path/to/kryo-mark-ascii.png]
//
// Reads the site's white-on-transparent mark (public/brand/kryo-mark-ascii.png
// here, copied from kryo.to), turns every run of lit pixels into a rectangle,
// merges runs that repeat down the rows, and writes src/ui/ascii/mark.ts.
// Re-run when kryo.to's mark changes.

import sharp from 'sharp'
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const src = process.argv[2] ?? path.join(root, 'public', 'brand', 'kryo-mark-ascii.png')
const { data, info } = await sharp(src).ensureAlpha().raw().toBuffer({ resolveWithObject: true })
const { width, height, channels } = info
const lit = (x, y) => data[(y * width + x) * channels + 3] > 127

// Runs per row.
let open = new Map() // "x0,x1" -> rect being grown downwards
const rects = []
for (let y = 0; y <= height; y++) {
  const runs = new Set()
  if (y < height) {
    let x = 0
    while (x < width) {
      if (!lit(x, y)) {
        x++
        continue
      }
      const x0 = x
      while (x < width && lit(x, y)) x++
      runs.add(`${x0},${x}`)
    }
  }
  const next = new Map()
  for (const key of runs) {
    const r = open.get(key)
    if (r) {
      r.h++
      next.set(key, r)
      open.delete(key)
    } else {
      const [x0, x1] = key.split(',').map(Number)
      next.set(key, { x: x0, y, w: x1 - x0, h: 1 })
    }
  }
  for (const r of open.values()) rects.push(r)
  open = next
}

const minX = Math.min(...rects.map((r) => r.x))
const minY = Math.min(...rects.map((r) => r.y))
const maxX = Math.max(...rects.map((r) => r.x + r.w))
const maxY = Math.max(...rects.map((r) => r.y + r.h))
const d = rects.map((r) => `M${r.x - minX} ${r.y - minY}h${r.w}v${r.h}h${-r.w}z`).join('')

const out = `// Generated by scripts/trace-mark.mjs from kryo.to's K// mark. Do not edit.
// ${rects.length} rectangles traced from a ${width}x${height} source.

export const MARK_W = ${maxX - minX}
export const MARK_H = ${maxY - minY}
export const MARK_PATH =
  '${d}'
`
writeFileSync(path.join(root, 'src', 'ui', 'ascii', 'mark.ts'), out)
console.log(`${rects.length} rects, ${maxX - minX}x${maxY - minY}, ${(d.length / 1024).toFixed(1)} KB of path`)
